Assignment by Ganesh
automationtestplanet/Java_Project_Oct_2023 pull request #9
Opened 2023-10-27 16:01 UTC by ganeshgit4

Assignment completed

2023-10-31 01:48 UTC, automationtestplanet requested changes

2023-10-31 01:48 UTC, automationtestplanet commented on src/assignments/ganesh/Assignment1.java
> +				System.out.println("Even numbers from the array are:"+array1[i]);
Convert to method

2023-11-02 04:41 UTC, ganeshgit4 commented on src/assignments/ganesh/Assignment1.java
> +	static void displayEvenNumbers() {
Converted into method

2023-11-04 02:17 UTC, automationtestplanet approved these changes

2023-11-04 02:17 UTC, merged